# Basics of Python

In [ ]:
a=10
b=20
c=a+b
print(c)

30


In [ ]:
print('Hello World')

Hello World


In [ ]:
# end parameter
print('Hello',end=' ')
print('World')

Hello World


In [ ]:
# sep parameter
print('Neha','Kotha',sep='.')

Neha.Kotha


# Basic Operators

In [ ]:
# @title Arithmetic Operators
a = 10
b = 4
sum = a + b
print("Sum is", sum)
diff = a - b
print('Difference is',diff)
qnt = a / b
print("Quotient is", qnt)
prod = a * b
print('Product is', prod)
remainder = a % b
print('Remainder is', remainder)
floor = a // b
print('Floor value is', floor)
exp = 2 ** 3
print("Exponent value is", exp)

Sum is 14
Difference is 6
Quotient is 2.5
Product is 40
Remainder is 2
Floor value is 2
Exponent value is 8


In [ ]:
# @title Comparison Operators
num1 = 30
num2 = 30
ex1 = (num1 == num2)
print(ex1)
ex2 = (num1 != num2)
print(ex2)
ex3 = (num1 >= num2)
print(ex3)
ex4 = (num1 <= num2)
print(ex4)

True
False
True
True


In [ ]:
# @title Logical Operators
num=int(input('Enter a number'))
cond=(num>5) and (num<20)
print('Output for number greater than 5 and number lesser than 20 is',cond)
age=int(input('Enter your age'))
cond=(age>18) or (age==18)
print('Age greater than 18 or equal to 18 is',cond)
a=False
print(not(a))

Enter a number12
Output for number greater than 5 and number lesser than 20 is True
Enter your age20
Age greater than 18 or equal to 18 is True
True


In [ ]:
# @title Assignment Operators
a=10
a +=1
print(a)

b=5
b *=2
print(b)

11
10


# **Conditional Statements**

In [ ]:
# Check if the number is greater than 0
num=int(input('Enter a Number'))
if num>0:
  print('Number is greater than 0')
elif num==0:
  print('Number is zero')
else:
  print('Number is less than 0')

Enter a Number12
Number is greater than 0


In [ ]:
# Check if your age is eligible to vote
age=int(input('Enter your age'))
if age >=18:
  print(f'Age:{age},Eligible to vote')
else:
  print(f'Not eligible to vote since you require {18-age} more years to vote.')

Enter your age15
Not eligible to vote since you require 3 more years to vote.


In [ ]:
# Check if the number is Even or Odd
num = int(input('Enter a number'))
if num % 2 == 0:
  print(f'Number:{num}, Is an even Number')
else:
  print(f'Number:{num}, Is a odd Number')

Enter a number20
Number:20, Is an even Number


In [ ]:
# Check if the number is Factor of 7
num=int(input('Enter any number'))
if num%7==0:
  print(f'Factor of 7 for the number :{num}')
else:
  print(f'{num} Is not factor of 7')

Enter any number35
Factor of 7 for the number :35


In [ ]:
# Exercise 1
# If the employee is working in the company for more than 5 years then he/she will get a bonus of 50% to thier current salary
yoe = float(input('Enter years of experience'))
if yoe > 5:
  salary = float(input('Enter the Salary'))
  print(f'Current Salary: {salary}, Bonus(50%): {salary * 0.5}, Salary after Bonus: {salary + (salary * 0.5)}')
else:
  print('No Bonus Since years of experience is lesser than 5')

Enter years of experience5
No Bonus Since years of experience is lesser than 5


In [ ]:
# Exercise 2
# If the electricty units is less than or equal to 100 then no charge, else if the electricity unit is greater than 100 and lesser than
# or equal to 200 then Rs.10 per unit. If the units is greater than 200 then Rs.15 per unit
units = float(input('Enter the no.of units'))
if units > 0 and units <= 100:
  print('No Charge')
elif units > 100 and units <= 200:
  print(f'Extra units used {units - 100}, Charge: {(units - 100) * 10}') # 115
elif units > 200:
  print(f'Extra units used {units - 100}, Charge: {(1000) + ((units - 200) * 15)}') # 201
else:
  print('Invalid unit')

Enter the no.of units220
Extra units used 120.0, Charge: 1300.0


In [ ]:
# Exercise 3
# BMI Calculator
# BMI = (Weight(KG)) / (Height(M) ** 2)
# BMI < 18.5 Then Underweight
# BMI between 18.5 and 24.9 then normal weight
# BMI between 24.9 and 29.9 then overweight
# BMI > 29.9 Obese
height_m = float(input("Enter the height in meters"))
weight_kg = float(input("Enter the weight in Kgs"))
BMI = weight_kg / (height_m ** 2)
if BMI < 18.5:
  #print("BMI Score is", BMI, "Underweight")
  print(f"BMI Score is {BMI} Underweight")
elif BMI >=18.5 and BMI < 24.9:
  print(f"BMI Score is {BMI} Normal Weight")
elif BMI >=24.9 and BMI < 29.9:
  print(f"BMI Score is {BMI} Over Weight")
else:
  print(f"BMI Score is {BMI} Obese")

Enter the height in meters1.9
Enter the weight in Kgs65
BMI Score is 18.005540166204987 Underweight


In [ ]:
# Exercise 4
# Find whether the character is a vowel or a consonant
char = input('Enter any letter')
char_lower = char.lower()
vowels = ['a','e','i','o','u']
if char_lower in vowels:
  print('Given Letter is a Vowel')
else:
  print('Given Letter is a Consonant')

Enter any letterN
Given Letter is a Consonant


# Data Types

In [ ]:
# Boolean datatype
a=True
b=False
print(type(a))

<class 'bool'>


In [ ]:
# Number datatype
a=1
b=1.1
print(type(b))

<class 'float'>


In [ ]:
# String Datatype
a = 'Hello World'
    #012345678910
print(type(a))

# Indexing
# Access only letter W from the string
print(a[6])
# Access letter d
print(a[-1])
# Access Hello
print(a[0:5]) # start:end-1
# Acess World
print(a[6:11]) # a[6:] End-1 value will take the last value by default

<class 'str'>
W
d
Hello
World


In [ ]:
# Function in String datatype
str1 = 'My NaMe is RInEx'
# lower
print(str1.lower())
# upper
print(str1.upper())
# Length
print(len(str1))

my name is rinex
MY NAME IS RINEX
16


In [ ]:
# List Datatype
emp_name = ['Sam','John','Ram','Adam']
print(emp_name)

# Accessing List Elements - Sam
print(emp_name[0])

# Accessing List Elements - Ram
print(emp_name[2])

# Accessing List Elements - John and Ram
print(emp_name[1:3]) # start : end - 1

['Sam', 'John', 'Ram', 'Adam']
Sam
Ram
['John', 'Ram']


In [ ]:
# Dictionary Datatype
'''
employees = ['Adam',25,'John',28,'Ram',26]
# Find the age of John
print(employees[3])
'''
employees = {'Adam':20,'John':28,'Ram':26} # key:value pair
# Get the age of adam
print(employees['Ram'])
# Print Keys
print(employees.keys())
# Print Values
print(employees.values())
# Print both
print(employees.items())

26
dict_keys(['Adam', 'John', 'Ram'])
dict_values([20, 28, 26])
dict_items([('Adam', 20), ('John', 28), ('Ram', 26)])


In [ ]:
# @title Exercise 1
# User Authentication
database = {
            'user1' : '123456',
            'user2' : '123@abc',
            'user3' : '654321'
            }
username = input('Enter your username')
if username in database.keys():
  password = input('Enter your password')
  if password == database[username]: # database['user'1] = 123456
    print('Welcome', username)
  else:
    print('Invalid Password')
else:
  print('Invalid Username')

Enter your usernameuser1
Enter your password123@abc
Invalid Password


In [ ]:
database = {
            'user1' : '123456',
            'user2' : '123@abc',
            'user3' : '654321'
            }

print(database['user1'])

123456


# Looping Statements

In [ ]:
# Print Hello 10 times
for i in range(10):
  print('Hello')

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


In [ ]:
# Print Hello 10 times
i=0
while i<10:
  print('Hello')
  i+=1

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


In [ ]:
# Print Number 0 to 9
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# Print Number 0 to 9
i = 0
while i < 10:
  print(i)
  i += 1

0
1
2
3
4
5
6
7
8
9


In [ ]:
# Print Number 1 to 10
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
# Print Number 10 to 1
for i in range(10,0,-1):
  print(i)

10
9
8
7
6
5
4
3
2
1


In [ ]:
# Print Number 10 to 1
i=10
while i>0:
  print(i)
  i-=1

10
9
8
7
6
5
4
3
2
1


In [ ]:
# Print Number 2 to 20 (Mutiples of 2)
for i in range(2,21,2):
  print(i)

2
4
6
8
10
12
14
16
18
20


In [ ]:
# Print Number 2 to 20 (Mutiples of 2)
i=2
while i<=20:
  print(i)
  i+=2

2
4
6
8
10
12
14
16
18
20


In [ ]:
# Print Number 20 to 2 (Mutiples of 2)
for i in range(20,1,-2):
  print(i)

20
18
16
14
12
10
8
6
4
2


In [ ]:
# Print Number 20 to 2 (Mutiples of 2)
i=20
while i>=2:
  print(i)
  i-=2

20
18
16
14
12
10
8
6
4
2


In [ ]:
# Print 10 to 170 but only the 13 multiples
for i in range(10,171):
  if i % 13 == 0:
    print(i)

13
26
39
52
65
78
91
104
117
130
143
156
169


In [ ]:
# Print 10 to 170 but only the 13 multiples
i = 10
while i <= 170:
  if i % 13 == 0:
    print(i)
  i += 1

13
26
39
52
65
78
91
104
117
130
143
156
169


In [ ]:
for i in range(5):
  print('*')

*
*
*
*
*


In [ ]:
for i in range(5):
  print('*',end=' ')

* * * * * 

In [ ]:
for i in range(5):
  print('*'*5)

*****
*****
*****
*****
*****


In [ ]:
for i in range(1,6):
  print('*'*i)

*
**
***
****
*****


In [ ]:
for i in range(5,0,-1):
  print('*'*i)

*****
****
***
**
*


In [ ]:
# @title Nested for Loop
for i in range(1,6):
  for j in range(i):
    print(i,end=" ")
  print(end='\n')

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [ ]:
for i in range(1,6): # Rows
  for j in range(i): # Columns
    print(j + 1, end = " ")
  print(end = '\n')

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
num_list = [34,34,6,56,34,656,67,54,5,7,98,32]
sum = 0
for i in num_list:
  sum = sum + i
print(sum)

1083


In [ ]:
# Program to find factorial of a number using while loop
num = int(input('Enter the value'))
fact = 1
while num: #True
  fact = fact * num # 120 * 1 = 120
  num -= 1 # 1-1 = 0
print(fact)

Enter the value6
720


In [ ]:
# Check whether the given number is prime or not
num = int(input('Enter a Number'))
if num <= 1:
  print('Number is not Prime Number')
else:
  is_prime = True # Assuming it's prime
  for i in range(2,num):
    if num % i == 0:
      is_prime = False
      break

  if is_prime:
    print(num,'is a prime number')
  else:
    print(num,'is a composite number')

Enter a Number25
25 is a composite number


In [ ]:
# Display Menu Program
while True:
  option = int(input("""
  Calculator

  Option 1: Sum
  Option 2: Difference
  Option 3: Product
  Option 4: Quotient
  Option 5: Quit

  Enter your choice
  """))
  if option == 5:
    print('Thank you for using My calculator')
    break
  if option > 4 or option <= 0:
    print('Invalid option, Enter the correct option')
  if option >= 1 and option <= 4:
    num1 = int(input('Enter Number 1'))
    num2 = int(input('Enter Number 2'))
    if option == 1:
      sum = num1 + num2
      print('Sum is',sum)
    elif option == 2:
      diff = num1 - num2
      print('Differecnce is',diff)
    elif option == 3:
      prod = num1 * num2
      print('Product is',prod)
    elif option == 4:
      qnt = num1 / num2
      print('Quotient is',qnt)


  Calculator

  Option 1: Sum
  Option 2: Difference
  Option 3: Product
  Option 4: Quotient
  Option 5: Quit

  Enter your choice
  6
Invalid option, Enter the correct option

  Calculator

  Option 1: Sum
  Option 2: Difference
  Option 3: Product
  Option 4: Quotient
  Option 5: Quit

  Enter your choice
  2
Enter Number 110
Enter Number 25
Differecnce is 5

  Calculator

  Option 1: Sum
  Option 2: Difference
  Option 3: Product
  Option 4: Quotient
  Option 5: Quit

  Enter your choice
  5
Thank you for using My calculator


In [ ]:
# @title Functions

In [ ]:
# @title Example 1
# Code to return whether the given number is odd or even
def oddeve(num):
  if num % 2 == 0:
    print("Even")
  else:
    print("Odd")

In [ ]:
# Code to return whether the given number is odd or even from the
def oddeve():
  num = int(input('Enter a Number'))
  if num == 0:
    print("Number is 0")
  elif num % 2 != 0:
    print("Odd")
  else:
    print("Even")

In [ ]:
oddeve()

Enter a Number5
Odd


In [ ]:
# @title Lambda Functions
add=lambda x,y:x+y
print(add(5,7))

12


In [ ]:
# create a function for all basic arithmetic operations
def math():
  num1 = int(input('Enter Number 1'))
  num2 = int(input('Enter Number 2'))
  sum = num1 + num2
  diff = num1 - num2
  prod = num1 * num2
  qnt = num1 / num2
  print('Sum is', sum)
  print('Difference is', diff)
  print('Product is', prod)
  print('Quotient is', qnt)

In [ ]:
def greet():
  print('Hello')

In [ ]:
greet_1=lambda:'Hello'

In [ ]:
greet_1()

'Hello'

# **Data Science**

# Numpy

In [ ]:
a = [1,2,3,4,5] # a (list)
# Add +1 to each list elements
sum = 0
for i in a:
  print(i+1, end = " ")

2 3 4 5 6 

In [ ]:
# @title Steps to Import numpy and use it
# Step 1: Import Numpy
import numpy as np # alias name (nickname)
a = [1,2,3,4,5] #list
# Step 2: Convert list into array
arr = np.array(a)
# Step 3: Numerical operations
print(arr + 1)
# Subtract -2 from each list element
print(arr // 2)

[2 3 4 5 6]
[0 1 1 2 2]


In [ ]:
# @title Example 1
# Mathematical Operations using Numpy
x = [1,6,9,5,8]
import numpy as np
arr = np.array(x)
print('Addition',arr + 1)
print('Subtraction',arr - 1)
print('Division',arr / 2)
print('Product',arr * 5)

Addition [ 2  7 10  6  9]
Subtraction [0 5 8 4 7]
Division [0.5 3.  4.5 2.5 4. ]
Product [ 5 30 45 25 40]


In [ ]:
# @title Example 2
# Converting a list into an array without declaring the list
import numpy as np
arr1 = np.array([2,5,1,3,9,4])
arr2 = np.array([6,3,2,1,7,9])
# Find maximum value out of array 1
print(arr1.max())
# Find minimum value out of array 2
print(arr2.min())
# Find avg of array 1
print(arr1.mean())

9
1
4.0


In [ ]:
# @title Example 3
# Find the dimension of the array
x = [1,2,3,4,5] # 1D list
arr = np.array(x)
print(arr.ndim)

1


In [ ]:
# @title Example 4
# Find the dimension of the array'
x = [[1,2,3],
     [4,5,6]]
arr = np.array(x)
print(arr.ndim)

2


In [ ]:
# @title Random Number Library
import numpy as np
from numpy import random
x = (random.randint(10))
arr = np.array(x)
print(arr)

0


In [ ]:
# @title Example 1
# Create 1D array using random library
x = random.randint(100, size = (5))
arr = np.array(x)
print(arr)

[51 58 62 25 12]


In [ ]:
# @title Example 2
# Create 2D array using random library
x = random.randint(10, size = (3,5)) # rows, columns
arr = np.array(x)
print(arr)

[[7 3 3 4 2]
 [3 0 2 7 9]
 [0 6 4 2 3]]


In [ ]:
# @title Example 3
# Create 3D array using random library
x = random.randint(10, size = (2,3,5)) # Inner array, rows, columns
arr = np.array(x)
print(arr.ndim)

3


In [ ]:
# @title A-range function
'''
It is similar to range function but returns array
'''
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# @title Example 1
# Create a 1D array from 2 to 20 with multiples of 2
arr = np.arange(2,21,+2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
# @title Example 2
# Change the datatype
x = np.arange(1.5,11, dtype = int)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# @title Example 3
# Create a 1D array from 5 to 50 with multiples of 5
x = np.arange(5,51,5, dtype = int)
print(x)

[ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
# @title Example 4
# Print array containing ones
x = np.ones([3,5], dtype = int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# @title Example 4
# Print array containing zeros
x = np.zeros([5,3], dtype = int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# @title Example 5
# Print Identity Matrix
x = np.identity(4, dtype= int)
print(x)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# @title Example 6
x = np.eye(4,k = 1, dtype = int)
print(x)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [ ]:
# Convert 1D array into 2D array
x=np.arange(10)
print(x)
reshaped=x.reshape(5,2)
print(reshaped)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# Convert 1D array into 3D array
import numpy as np
x=np.arange(20)
print('Original array',x)
reshaped=x.reshape(2,2,5)
print(reshaped)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [ ]:
# Convert 2D array into 1D array
x = np.array([[0, 1],
 [2 ,3],
 [4 ,5],
 [6 ,7],
 [8 ,9]])
print('Oroginal Array', x)
reshape = x.reshape(10)
print("Reshaped array",reshape)

Oroginal Array [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Reshaped array [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Convert 3D array into 1D array
x = np.array([[[0, 1],
 [2 ,3],
 [4 ,5],
 [6 ,7],
 [8 ,9]]])
print('Original Array', x)
reshape = x.reshape(10)
print("Reshaped array",reshape)

Original Array [[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
Reshaped array [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Convert 2D array into 3D array
x = np.array([[0, 1],
 [2 ,3],
 [4 ,5],
 [6 ,7],
 [8 ,9]])
print('Oroginal Array', x)
reshape = x.reshape(2,1,5)
print("Reshaped array",reshape)

Oroginal Array [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Reshaped array [[[0 1 2 3 4]]

 [[5 6 7 8 9]]]


In [ ]:
# @title Accessing Array Elements
'''
1) Slicing
2) Integer Array Indexing
3) Boolean Array Indexing
'''

In [ ]:
# Slicing
import numpy as np
arr1 = np.array([1,2,3,4,5])
                #0,1,2,3,4
# Access only 2 from the given array
print(arr1[1])
# Access only 5 from the given array
print(arr1[4])
arr2 = np.array([[1,2,3,4,5],   #0
                 [6,7,8,9,10]]) #1
# Access only 5 from the given array
print(arr2[0][4])
# Access only 9 from the given array
print(arr2[1][3])

2
5
5
9


In [ ]:
# Integer Array Indexing
import numpy as np
arr1 = np.array([1,2,3,4,5])
                #0,1,2,3,4
# Access only 2 from the given array
print(arr1[1])
# Access only 5 from the given array
print(arr1[4])
arr2 = np.array([[1,2,3,4,5],   #0
                 [6,7,8,9,10]]) #1
# Access only 5 from the given array
print(arr2[0,4])
# Access only 9 from the given array
print(arr2[1,3])

2
5
5
9


In [ ]:
# Boolean Array Indexing
arr = np.array([[32,5,23,1,43,12,34,34,345,23,23],
                [12,34,34,23,23,34,76,54,76,87,56]])
print("Extract only those values which are greater than 70")
cond = (arr > 70)
print('Values that are greater than 70 are', arr[cond])

Extract only those values which are greater than 70
Values that are greater than 70 are [345  76  76  87]


In [ ]:
arr = np.array([[32,5,23,1,43,12,34,34,345,23,23],
                [12,34,34,23,23,34,76,54,76,87,56]])
print("Extract only those values which are not divisible by 2 or basically extract odd numbers")
cond = (arr % 2 == 1)
print('Odd numbers from the array are', arr[cond])

Extract only those values which are not divisible by 2 or basically extract odd numbers
Odd numbers from the array are [  5  23   1  43 345  23  23  23  23  87]


# **Student Report Dataset**

In [ ]:
import numpy as np
                          # Student_Name,Mat,Sci,CS,Eng,SST
students_array = np.array([['Student_1', 59, 64, 94, 87, 81],

                          ['Student_2', 8, 56, 18, 58, 69],

                          ['Student_3', 7, 20, 60, 63, 42],

                          ['Student_4', 71, 94, 71, 68, 13],

                          ['Student_5', 89, 1, 16, 33, 40],

                          ['Student_6', 4, 25, 48, 41, 84],

                          ['Student_7', 3, 79, 46, 9, 71],

                          ['Student_8', 87, 77, 75, 15, 69],

                          ['Student_9', 61, 1, 48, 98, 23],

                          ['Student_10', 98, 60, 24, 66, 56],

                          ['Student_11', 58, 12, 75, 7, 98],

                          ['Student_12', 23, 62, 6, 35, 37],

                          ['Student_13', 14, 25, 87, 56, 8],

                          ['Student_14', 68, 1, 81, 11, 61],

                          ['Student_15', 11, 69, 35, 17, 66]], dtype=object)

In [ ]:
# @title Task 1
# Accessing all the names of the students
students_array[:,0] # Syntax [row,column]

array(['Student_1', 'Student_2', 'Student_3', 'Student_4', 'Student_5',
       'Student_6', 'Student_7', 'Student_8', 'Student_9', 'Student_10',
       'Student_11', 'Student_12', 'Student_13', 'Student_14',
       'Student_15'], dtype=object)

In [ ]:
# @title Task 2
# Find the average of subject 1(Maths)
Maths_marks = students_array[:,1]
print('Maths Marks of entire class is', Maths_marks)
print('Average Maths Marks of entire class is', (Maths_marks).mean())

Maths Marks of entire class is [59 8 7 71 89 4 3 87 61 98 58 23 14 68 11]
Average Maths Marks of entire class is 44.06666666666667


In [ ]:
# @title Task 3
# Find the average of subject 4(Eng)
Eng_marks = students_array[:,4]
print('English Marks of entire class is', Eng_marks)
print('Average English Marks of entire class is', (Eng_marks).mean())

English Marks of entire class is [87 58 63 68 33 41 9 15 98 66 7 35 56 11 17]
Average English Marks of entire class is 44.266666666666666


In [ ]:
# @title Task 4
# Find the average of student 7
Student_7 = students_array[6,1:]
print('Student 7 Marks are', Student_7)
print('Average is', (Student_7).mean())

Student 7 Marks are [3 79 46 9 71]
Average is 41.6


In [ ]:
# @title Task 5
# Find the average of student 7 for subject 2 to 4
Student_7 = students_array[6,2:5]
print('Student 7 Marks are', Student_7)
print('Average is', (Student_7).mean())

Student 7 Marks are [79 46 9]
Average is 44.666666666666664


In [ ]:
# @title Task 6
# Find the name and count of students where subject 1 marks is greater than subject 2 marks
sub1 = students_array[:,1]
sub2 = students_array[:,2]
cond = sub1 > sub2
print('Student Names who scored higher is subject 1 than subject 2 are', students_array[cond,0])
print('Count of Student who scored higher is subject 1 than subject 2 are', len(students_array[cond,0]))

Student Names who scored higher is subject 1 than subject 2 are ['Student_5' 'Student_8' 'Student_9' 'Student_10' 'Student_11'
 'Student_14']
Count of Student who scored higher is subject 1 than subject 2 are 6


In [ ]:
# @title Task 7
# Find the student average of first 10 students
first_10_stu = students_array[:10,1:]
print('Overall Average of first 10 students', (first_10_stu).mean())
print('Student Average of first 10 students', (first_10_stu).mean(axis = 1)) # axis = 1(row wise average)
print('Subject Average of first 10 students', (first_10_stu).mean(axis = 0)) # axis = 0(Column wise average)

Overall Average of first 10 students 51.0
Student Average of first 10 students [77.0 41.8 38.4 63.4 35.8 40.4 41.6 64.6 46.2 60.8]
Subject Average of first 10 students [48.7 47.7 50.0 53.8 54.8]


In [ ]:
# @title Task 8
# Find the Subject average of 1,3 and 4 subject.
sub_avg = students_array[:,[1,3,4]]
print('Subject Average of 1,3 and 4th subject is', sub_avg.mean(axis = 0))

Subject Average of 1,3 and 4th subject is [44.06666666666667 52.266666666666666 44.266666666666666]


In [ ]:
# @title Task 9
# Find the subject average of student 5 to student 14
sub_avg_of_stu_5_to_14 = students_array[4:14,1:]
print('Subject Average of Student 5 to Student 14', sub_avg_of_stu_5_to_14.mean(axis = 0))

Subject Average of Student 5 to Student 14 [50.5 34.3 50.6 37.1 54.7]


In [ ]:
# @title Task 10
# Find all the student names who scored higher than student 15 in both subject1 and subject2
sub1 = students_array[:,1]
sub2 = students_array[:,2]
stu_15_sub1 = students_array[14,1]
stu_15_sub2 = students_array[14,2]
cond = (sub1 > stu_15_sub1) & (sub2 > stu_15_sub2)
print("Student 15 Subject 1 and Subject 2 marks are",stu_15_sub1,'and',stu_15_sub2)
print(students_array[cond,0:3])

Student 15 Subject 1 and Subject 2 marks are 11 and 69
[['Student_4' 71 94]
 ['Student_8' 87 77]]


In [ ]:
# @title Task 11
# Find all the student names who scored higher than student 11 either in subject 1 or subject 5
sub1 = students_array[:,1]
sub5 = students_array[:,5]
stu_11_sub1 = students_array[10,1]
stu_11_sub5 = students_array[10,5]
cond = (sub1 > stu_11_sub1) | (sub5 > stu_11_sub5)
print("Student 11 Subject 1 and Subject 5 marks are",stu_11_sub1,'and',stu_11_sub5)
result = students_array[cond]
print(result[:,[0,1,5]])

Student 11 Subject 1 and Subject 5 marks are 58 and 98
[['Student_1' 59 81]
 ['Student_4' 71 13]
 ['Student_5' 89 40]
 ['Student_8' 87 69]
 ['Student_9' 61 23]
 ['Student_10' 98 56]
 ['Student_14' 68 61]]


In [ ]:
# @title Bank Customer Dataset
# Age , Employment , Marital Status, Balance, Personal Loan, Car Loan, Connection, Month of Join
import numpy as np
banking_array = np.array([[30.0, 'unemployed', 'married', 1787.0, 'no', 'no', 'cellular','oct'],

       [33.0, 'services', 'married', 4789.0, 'yes', 'yes', 'cellular','may'],

       [35.0, 'management', 'single', 1350.0, 'yes', 'no', 'cellular','apr'],

       [30.0, 'management', 'married', 1476.0, 'yes', 'yes', 'unknown','jun'],

       [59.0, 'blue-collar', 'married', 0.0, 'yes', 'no', 'unknown','may'],

       [35.0, 'management', 'single', 747.0, 'no', 'no', 'cellular','feb'],

       [36.0, 'self-employed', 'married', 307.0, 'yes', 'no', 'cellular','may'],

       [39.0, 'technician', 'married', 147.0, 'yes', 'no', 'cellular','may'],

       [41.0, 'entrepreneur', 'married', 221.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'services', 'married', -88.0, 'yes', 'yes', 'cellular','apr'],

       [39.0, 'services', 'married', 9374.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'admin.', 'married', 264.0, 'yes', 'no', 'cellular', 'apr'],

       [36.0, 'technician', 'married', 1109.0, 'no', 'no', 'cellular','aug'],

       [20.0, 'student', 'single', 502.0, 'no', 'no', 'cellular', 'apr'],

       [31.0, 'blue-collar', 'married', 360.0, 'yes', 'yes', 'cellular','jan'],

       [40.0, 'management', 'married', 194.0, 'no', 'yes', 'cellular','aug'],

       [56.0, 'technician', 'married', 4073.0, 'no', 'no', 'cellular','aug'],

       [37.0, 'admin.', 'single', 2317.0, 'yes', 'no', 'cellular', 'apr'],

       [25.0, 'blue-collar', 'single', -221.0, 'yes', 'no', 'unknown','may'],

       [31.0, 'services', 'married', 132.0, 'no', 'no', 'cellular','jul']], dtype=object)

In [ ]:
# @title Task 1
# Finding unique values from the employment column
np.unique(banking_array[:,1])

array(['admin.', 'blue-collar', 'entrepreneur', 'management',
       'self-employed', 'services', 'student', 'technician', 'unemployed'],
      dtype=object)

In [ ]:
# @title Task 2
# Find the count of customers who has taken a personal loan
cust_with_personal_loan = (banking_array[:,4] == 'yes')
print('Count of customers who has taken a personal loan is',np.count_nonzero(cust_with_personal_loan))

Count of customers who has taken a personal loan is 13


In [ ]:
# @title Task 3
# Find the count of cutomers who has connection and has taken car loan
car_loan = (banking_array[:,5] == 'yes')
connection = (banking_array[:,6] == 'cellular')
cond = (car_loan) & (connection)
print('Count of cutomers who has connection and has taken car loan',np.count_nonzero(cond))

Count of cutomers who has connection and has taken car loan 4


In [ ]:
# @title Task 4
# Find the count of customers with personal loan and are married and has car loan
cust_with_personal_loan = (banking_array[:,4] == 'yes')
car_loan = (banking_array[:,5] == 'yes')
married = (banking_array[:,2] == 'married')
cond = (cust_with_personal_loan & car_loan & married)
print('Count of customers with personal loan and are married and has car loan are',np.count_nonzero(cond))

Count of customers with personal loan and are married and has car loan are 4


In [ ]:
# @title Task 5
# Find the count of customers whose age is greater than 35 and less than 50 and also find the overall bank balance of these customers
age = ((banking_array[:,0]) > 35) & ((banking_array[:,0]) < 50)
overall_balance = (banking_array[:,3])
print('Count of customers whose age is greater than 35 and less than 50 is', np.count_nonzero(age))
# Accessing total balance by age condition
cond = overall_balance[age]
print('Overall bank balance of these customers is',cond.sum())

Count of customers whose age is greater than 35 and less than 50 is 9
Overall bank balance of these customers is 13845.0


In [ ]:
# @title Task 6
# Find the count who are single but have more than average bank balance
single = (banking_array[:,2] == 'single')
balance = (banking_array[:,3])
avg_bal = balance.mean()
print("Average bank balance is", avg_bal)
cond = (single) & (balance > avg_bal)
print('Customers with balance greater than the average bank balance are', np.count_nonzero(cond))

Average bank balance is 1442.0
Customers with balance greater than the average bank balance are 1


In [ ]:
# @title Task 7
'''
Company has decided to give a bonus of 5% of their account balance to those account holders where age is more than or equal
to 55 years and whose account balance is more than 2000. Calculate the sum of the total bank balance to the account holders
after crediting thier bonus amount.
'''
age = (banking_array[:,0])
balance = (banking_array[:,3])
cond = (age >= 55) & (balance > 2000)
tot_bal = balance[cond]
bonus = 0.05 * tot_bal
tot_after_bonus = (tot_bal + bonus)
print("Total balance before the bonus", tot_bal)
print("Sum of total bank balance to the account holders after crediting their bonus amount is", tot_after_bonus)

Total balance before the bonus [4073.0]
Sum of total bank balance to the account holders after crediting their bonus amount is [4276.65]


In [ ]:
# @title Task 8
'''
Company has decided if the age of the customer is less than 25 then his balance will be credited with 2000
and if it is above then credit 1000.
'''
age = (banking_array[:,0])
balance = (banking_array[:,3])
cond1 = (age < 25)
cond2 = (age >= 25)
tot_bal_under_25 = balance[cond1]
tot_bal_above_25 = balance[cond2]
bonus1 = 2000 + tot_bal_under_25
bonus2 = 1000 + tot_bal_above_25
print("Customer with age less than 25 and 2000 credited to thier total balance is",bonus1)
print("Customer with age more or equal to 25 and 1000 credited to thier total balance is",bonus2)

Customer with age less than 25 and 2000 credited to thier total balance is [2502.0]
Customer with age more or equal to 25 and 1000 credited to thier total balance is [2787.0 5789.0 2350.0 2476.0 1000.0 1747.0 1307.0 1147.0 1221.0 912.0
 10374.0 1264.0 2109.0 1360.0 1194.0 5073.0 3317.0 779.0 1132.0]


# **Pandas**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Create a simple series
values = [100,200,300,400,500]
ser = pd.Series(values)
print(ser)

0    100
1    200
2    300
3    400
4    500
dtype: int64


In [ ]:
# Changing Index Value
values = [100,200,300,400,500]
ser = pd.Series(values, index = ['a','b','c','d','e'])
print(ser)

a    100
b    200
c    300
d    400
e    500
dtype: int64


In [ ]:
# Create a Simple DataFrame
values = [100,200,300,400,500]
name = ['A1','A2','A3','A4','A5']
df = pd.DataFrame([name,values])

# Converting horizontal row format into vertical column format
df = df.transpose()
df.columns = ['Name','Values']
df

Name Values
0   A1    100
1   A2    200
2   A3    300
3   A4    400
4   A5    500

# Analysis 1 (Titanic Dataset)

In [ ]:
# Read CSV file into DataFrame
import pandas as pd
df=pd.read_csv('Titanic.csv')
df

PassengerId  Survived  Pclass  \
0            1.0       0.0     3.0   
1            2.0       1.0     1.0   
2            3.0       1.0     3.0   
3            4.0       1.0     1.0   
4            5.0       0.0     3.0   
..           ...       ...     ...   
994          NaN       NaN     NaN   
995          NaN       NaN     NaN   
996          NaN       NaN     NaN   
997          NaN       NaN     NaN   
998          NaN       NaN     NaN   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0    1.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0    1.0   
2                               Heikkinen, Miss. Laina  female  26.0    0.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
4                             Allen, Mr. William Henry    male  35.0    0.0   
..                                                 ...     ...   ...    ...   
994                                                NaN     NaN   NaN    NaN   
995                                                NaN     NaN   NaN    NaN   
996                                                NaN     NaN   NaN    NaN   
997                                                NaN     NaN   NaN    NaN   
998                                                NaN     NaN   NaN    NaN   

     Parch            Ticket     Fare Cabin Embarked  
0      0.0         A/5 21171   7.2500   NaN        S  
1      0.0          PC 17599  71.2833   C85        C  
2      0.0  STON/O2. 3101282   7.9250   NaN        S  
3      0.0            113803  53.1000  C123        S  
4      0.0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
994    NaN               NaN      NaN   NaN      NaN  
995    NaN               NaN      NaN   NaN      NaN  
996    NaN               NaN      NaN   NaN      NaN  
997    NaN               NaN      NaN   NaN      NaN  
998    NaN               NaN      NaN   NaN      NaN  

[999 rows x 12 columns]

In [ ]:
# Shape function
df.shape
df.shape[0]
df.shape[1]

12

In [ ]:
# To get size of the dataset
df.size

11988

In [ ]:
# Describe Function
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
# Indexing of the Columns
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
994     NaN
995     NaN
996     NaN
997     NaN
998     NaN
Name: Age, Length: 999, dtype: float64

In [ ]:
# Indexing multiple Columns
df[['Name','Age','Fare']]

Name   Age     Fare
0                              Braund, Mr. Owen Harris  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                               Heikkinen, Miss. Laina  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                             Allen, Mr. William Henry  35.0   8.0500
..                                                 ...   ...      ...
994                                                NaN   NaN      NaN
995                                                NaN   NaN      NaN
996                                                NaN   NaN      NaN
997                                                NaN   NaN      NaN
998                                                NaN   NaN      NaN

[999 rows x 3 columns]

In [ ]:
# Get the maximun value from age column
df['Age'].max()

80.0

In [ ]:
# @title Step 1:Data Preprocessing
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    float64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    float64
 7   Parch        891 non-null    float64
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(7), object(5)
memory usage: 93.8+ KB


In [ ]:
# Check the null valus
df.isnull().sum()

PassengerId    108
Survived       108
Pclass         108
Name           108
Sex            108
Age            285
SibSp          108
Parch          108
Ticket         108
Fare           108
Cabin          795
Embarked       110
dtype: int64

In [ ]:
# Removing null values where entire row is null
df.dropna(how='all',inplace=True)

In [ ]:
df

PassengerId  Survived  Pclass  \
0            1.0       0.0     3.0   
1            2.0       1.0     1.0   
2            3.0       1.0     3.0   
3            4.0       1.0     1.0   
4            5.0       0.0     3.0   
..           ...       ...     ...   
886        887.0       0.0     2.0   
887        888.0       1.0     1.0   
888        889.0       0.0     3.0   
889        890.0       1.0     1.0   
890        891.0       0.0     3.0   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0    1.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0    1.0   
2                               Heikkinen, Miss. Laina  female  26.0    0.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
4                             Allen, Mr. William Henry    male  35.0    0.0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0    0.0   
887                       Graham, Miss. Margaret Edith  female  19.0    0.0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN    1.0   
889                              Behr, Mr. Karl Howell    male  26.0    0.0   
890                                Dooley, Mr. Patrick    male  32.0    0.0   

     Parch            Ticket     Fare Cabin Embarked  
0      0.0         A/5 21171   7.2500   NaN        S  
1      0.0          PC 17599  71.2833   C85        C  
2      0.0  STON/O2. 3101282   7.9250   NaN        S  
3      0.0            113803  53.1000  C123        S  
4      0.0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886    0.0            211536  13.0000   NaN        S  
887    0.0            112053  30.0000   B42        S  
888    2.0        W./C. 6607  23.4500   NaN        S  
889    0.0            111369  30.0000  C148        C  
890    0.0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
# Memory Usage
df.memory_usage()

Index          7128
PassengerId    7128
Survived       7128
Pclass         7128
Name           7128
Sex            7128
Age            7128
SibSp          7128
Parch          7128
Ticket         7128
Fare           7128
Cabin          7128
Embarked       7128
dtype: int64

In [ ]:
# Converting datatype
df[['PassengerId','Survived','Pclass','SibSp','Parch']]=df[['PassengerId','Survived','Pclass','SibSp','Parch']].astype('int8')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          119         0       2   
887          120         1       1   
888          121         0       3   
889          122         1       1   
890          123         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
# Printing the preview of the dataset
# Display first 20 rows
df.head(20)
# Display last 10 rows
df.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          114         0       3                        Markun, Mr. Johann   
882          115         0       3              Dahlberg, Miss. Gerda Ulrika   
883          116         0       2             Banfield, Mr. Frederick James   
884          117         0       3                    Sutehall, Mr. Henry Jr   
885          118         0       3      Rice, Mrs. William (Margaret Norton)   
886          119         0       2                     Montvila, Rev. Juozas   
887          120         1       1              Graham, Miss. Margaret Edith   
888          121         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          122         1       1                     Behr, Mr. Karl Howell   
890          123         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [ ]:
# Removing multiple colums
df.drop(['Ticket','Cabin'],inplace=True,axis=1, errors='ignore')

In [ ]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          119         0       2   
887          120         1       1   
888          121         0       3   
889          122         1       1   
890          123         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch     Fare Embarked  
0        0   7.2500        S  
1        0  71.2833        C  
2        0   7.9250        S  
3        0  53.1000        S  
4        0   8.0500        S  
..     ...      ...      ...  
886      0  13.0000        S  
887      0  30.0000        S  
888      2  23.4500        S  
889      0  30.0000        C  
890      0   7.7500        Q  

[891 rows x 10 columns]

In [ ]:
# Removing rows 0 and 2
df.drop([0,2],axis=0,inplace=True)

In [ ]:
df

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
..           ...       ...     ...   
886          119         0       2   
887          120         1       1   
888          121         0       3   
889          122         1       1   
890          123         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch     Fare Embarked  
1        0  71.2833        C  
3        0  53.1000        S  
4        0   8.0500        S  
5        0   8.4583        Q  
6        0  51.8625        S  
..     ...      ...      ...  
886      0  13.0000        S  
887      0  30.0000        S  
888      2  23.4500        S  
889      0  30.0000        C  
890      0   7.7500        Q  

[889 rows x 10 columns]

In [ ]:
# Renaming the column
df.rename(columns={'Pclass':'Class'},inplace=True)

In [ ]:
df

PassengerId  Survived  Class  \
1              2         1      1   
3              4         1      1   
4              5         0      3   
5              6         0      3   
6              7         0      1   
..           ...       ...    ...   
886          119         0      2   
887          120         1      1   
888          121         0      3   
889          122         1      1   
890          123         0      3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch     Fare Embarked  
1        0  71.2833        C  
3        0  53.1000        S  
4        0   8.0500        S  
5        0   8.4583        Q  
6        0  51.8625        S  
..     ...      ...      ...  
886      0  13.0000        S  
887      0  30.0000        S  
888      2  23.4500        S  
889      0  30.0000        C  
890      0   7.7500        Q  

[889 rows x 10 columns]

In [ ]:
# Find unique values from a given column
pd.unique(df['Survived'])

array([1, 0], dtype=int8)

In [ ]:
pd.unique(df['Class'])

array([1, 3, 2], dtype=int8)

In [ ]:
# Titanic analysis
# Find the no.of male and female in the dataset
df['Sex'].value_counts().reset_index()

Sex  count
0    male    576
1  female    313

In [ ]:
# Loc and iloc function
# Loc(location)
# iloc(index Location)
df.iloc[20:31,0:3]

PassengerId  Survived  Class
22           23         1      3
23           24         1      1
24           25         0      3
25           26         1      3
26           27         0      3
27           28         0      1
28           29         1      3
29           30         0      3
30           31         0      1
31           32         1      1
32           33         1      3

In [ ]:
# Find the no.of people with age greater than or equal to 18
# Step 1: Accessing the column
df['Age']
# Step 2: Apply condition
df['Age']>=18
# Step 3: Wrapping the condition with df
df[df['Age']>=18]

PassengerId  Survived  Class  \
1              2         1      1   
3              4         1      1   
4              5         0      3   
6              7         0      1   
8              9         1      3   
..           ...       ...    ...   
885          118         0      3   
886          119         0      2   
887          120         1      1   
889          122         1      1   
890          123         0      3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch     Fare Embarked  
1        0  71.2833        C  
3        0  53.1000        S  
4        0   8.0500        S  
6        0  51.8625        S  
8        2  11.1333        S  
..     ...      ...      ...  
885      5  29.1250        Q  
886      0  13.0000        S  
887      0  30.0000        S  
889      0  30.0000        C  
890      0   7.7500        Q  

[599 rows x 10 columns]

In [ ]:
df[(df['Class'] == 3) & (df['Age'] >= 18)]

PassengerId  Survived  Class  \
4              5         0      3   
8              9         1      3   
12            13         0      3   
13            14         0      3   
18            19         0      3   
..           ...       ...    ...   
881          114         0      3   
882          115         0      3   
884          117         0      3   
885          118         0      3   
890          123         0      3   

                                                  Name     Sex   Age  SibSp  \
4                             Allen, Mr. William Henry    male  35.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
..                                                 ...     ...   ...    ...   
881                                 Markun, Mr. Johann    male  33.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch     Fare Embarked  
4        0   8.0500        S  
8        2  11.1333        S  
12       0   8.0500        S  
13       5  31.2750        S  
18       0  18.0000        S  
..     ...      ...      ...  
881      0   7.8958        S  
882      0  10.5167        S  
884      0   7.0500        S  
885      5  29.1250        Q  
890      0   7.7500        Q  

[275 rows x 10 columns]

In [ ]:
# Passenger should be either in class 2 or Embarked 5
df[(df['Class']==2) | (df['Embarked']==5)]

PassengerId  Survived  Class  \
9             10         1      2   
15            16         1      2   
17            18         1      2   
20            21         0      2   
21            22         1      2   
..           ...       ...    ...   
866           99         1      2   
874          107         1      2   
880          113         1      2   
883          116         0      2   
886          119         0      2   

                                             Name     Sex   Age  SibSp  Parch  \
9             Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1      0   
15               Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0      0   
17                   Williams, Mr. Charles Eugene    male   NaN      0      0   
20                           Fynney, Mr. Joseph J    male  35.0      0      0   
21                          Beesley, Mr. Lawrence    male  34.0      0      0   
..                                            ...     ...   ...    ...    ...   
866                  Duran y More, Miss. Asuncion  female  27.0      1      0   
874         Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1      0   
880  Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0      1   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   

        Fare Embarked  
9    30.0708        C  
15   16.0000        S  
17   13.0000        S  
20   26.0000        S  
21   13.0000        S  
..       ...      ...  
866  13.8583        C  
874  24.0000        C  
880  26.0000        S  
883  10.5000        S  
886  13.0000        S  

[184 rows x 10 columns]

In [ ]:
# Display the data where class is either 2 or 3
df[df['Class'].isin([2,3])]

PassengerId  Survived  Class  \
4              5         0      3   
5              6         0      3   
7              8         0      3   
8              9         1      3   
9             10         1      2   
..           ...       ...    ...   
884          117         0      3   
885          118         0      3   
886          119         0      2   
888          121         0      3   
890          123         0      3   

                                                  Name     Sex   Age  SibSp  \
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch     Fare Embarked  
4        0   8.0500        S  
5        0   8.4583        Q  
7        1  21.0750        S  
8        2  11.1333        S  
9        0  30.0708        C  
..     ...      ...      ...  
884      0   7.0500        S  
885      5  29.1250        Q  
886      0  13.0000        S  
888      2  23.4500        S  
890      0   7.7500        Q  

[673 rows x 10 columns]

In [ ]:
# Filter out all the data where Fare is less than 100 and Embarked should be either S or C
df[(df['Fare']<=100) & (df['Embarked'].isin(['S','C']))]

PassengerId  Survived  Class  \
1              2         1      1   
3              4         1      1   
4              5         0      3   
6              7         0      1   
7              8         0      3   
..           ...       ...    ...   
884          117         0      3   
886          119         0      2   
887          120         1      1   
888          121         0      3   
889          122         1      1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
..                                                 ...     ...   ...    ...   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch     Fare Embarked  
1        0  71.2833        C  
3        0  53.1000        S  
4        0   8.0500        S  
6        0  51.8625        S  
7        1  21.0750        S  
..     ...      ...      ...  
884      0   7.0500        S  
886      0  13.0000        S  
887      0  30.0000        S  
888      2  23.4500        S  
889      0  30.0000        C  

[757 rows x 10 columns]

In [ ]:
# Sorting Function
# Sort age column in ascending order
df.sort_values(by='Age')

PassengerId  Survived  Class                                      Name  \
803           36         1      3           Thomas, Master. Assad Alexander   
755          -12         1      2                 Hamalainen, Master. Viljo   
644         -123         1      3                    Baclini, Miss. Eugenie   
469          -42         1      3             Baclini, Miss. Helene Barbara   
78            79         1      2             Caldwell, Master. Alden Gates   
..           ...       ...    ...                                       ...   
859           92         0      3                          Razi, Mr. Raihed   
863           96         0      3         Sage, Miss. Dorothy Edith "Dolly"   
868          101         0      3               van Melkebeke, Mr. Philemon   
878          111         0      3                        Laleff, Mr. Kristo   
888          121         0      3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch     Fare Embarked  
803    male  0.42      0      1   8.5167        C  
755    male  0.67      1      1  14.5000        S  
644  female  0.75      2      1  19.2583        C  
469  female  0.75      2      1  19.2583        C  
78     male  0.83      0      2  29.0000        S  
..      ...   ...    ...    ...      ...      ...  
859    male   NaN      0      0   7.2292        C  
863  female   NaN      8      2  69.5500        S  
868    male   NaN      0      0   9.5000        S  
878    male   NaN      0      0   7.8958        S  
888  female   NaN      1      2  23.4500        S  

[889 rows x 10 columns]

In [ ]:
# Sort Fare column in descending order
df.sort_values(by='Fare',ascending=False)

PassengerId  Survived  Class                                Name     Sex  \
737          -30         1      1              Lesurer, Mr. Gustave J    male   
679          -88         1      1  Cardeza, Mr. Thomas Drake Martinez    male   
258            3         1      1                    Ward, Miss. Anna  female   
341           86         1      1      Fortune, Miss. Alice Elizabeth  female   
438          -73         0      1                   Fortune, Mr. Mark    male   
..           ...       ...    ...                                 ...     ...   
806           39         0      1              Andrews, Mr. Thomas Jr    male   
815           48         0      1                    Fry, Mr. Richard    male   
481          -30         0      2    Frost, Mr. Anthony Wood "Archie"    male   
822           55         0      1     Reuchlin, Jonkheer. John George    male   
179          -76         0      3                 Leonard, Mr. Lionel    male   

      Age  SibSp  Parch      Fare Embarked  
737  35.0      0      0  512.3292        C  
679  36.0      0      1  512.3292        C  
258  35.0      0      0  512.3292        C  
341  24.0      3      2  263.0000        S  
438  64.0      1      4  263.0000        S  
..    ...    ...    ...       ...      ...  
806  39.0      0      0    0.0000        S  
815   NaN      0      0    0.0000        S  
481   NaN      0      0    0.0000        S  
822  38.0      0      0    0.0000        S  
179  36.0      0      0    0.0000        S  

[889 rows x 10 columns]

In [ ]:
# Group by function
# Find average age of male and female
df.groupby(by='Sex')['Age'].mean().reset_index()

Sex        Age
0  female  27.923077
1    male  30.745951